spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/source
#    username: postgres
#    password:
    source:
      url: jdbc:postgresql://localhost:5432/source
      username: postgres
      password:
    target:
      url: jdbc:postgresql://localhost:5432/target
      username: postgres
      password:
  jpa:
    show-sql: true
  batch:
    jdbc:
      initialize-schema: always